version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    # command: cd /app/build/src/server && ./server
    ports:
      - "8888:8888"
    volumes:
      - ./:/app
